version: '3'

services:
  php74:
    build:
      context: .
      dockerfile: docker/Dockerfile.php74
    ports:
      - "8074:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  php83:
    build:
      context: .
      dockerfile: docker/Dockerfile.php83
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public